version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./certs/generated:/app/certs/generated
    environment:
      - AWS_ACCESS_KEY_ID=yourkey
      - AWS_SECRET_ACCESS_KEY=yoursecret
      - AWS_DEFAULT_REGION=your-region
